version: 2
machine:
  services:
    - docker

jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:12b527414d07c69cde30b566a7955b08a7df138da1c5e5915685460276dda29a
      - image: mongo:3.4.4@sha256:c4bc4644b967a4b58022a79cf5c9afcd25ed08180c958a74df57b7753cfc8649
    environment:
      - NPM_CONFIG_LOGLEVEL: warn
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - run:
          name: Pruning Dependencies
          command: npm prune
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Compiling Code
          command: npm run build
      - run:
          name: Running tests
          command: npm run cover
      - run:
          name: Linting Code
          command: npm run lint
      - run:
          name: Checking Code Duplication
          command: npm run duplication -- --limit 10
      - deploy:
          name: Semantic Release
          command: npm run semantic-release
